export const STRINGS = {
  en: {
    // Auth screens
    splash_title: "MediTriage AI",
    splash_tagline: "Your Personal Medical Assistant",
    splash_card1_title: "AI Analysis",
    splash_card1_body: "Advanced assessment of your symptoms using state-of-the-art AI.",
    splash_card2_title: "Doctor Reviewed",
    splash_card2_body: "Every high-risk case is verified by certified medical professionals.",
    splash_card3_title: "Secure & Private",
    splash_card3_body: "Your health data is encrypted and completely confidential.",
    get_started: "Get Started",
    already_have_account: "Already have an account?",
    welcome_back: "Welcome Back",
    sign_in: "Sign In",
    sign_up: "Sign Up",
    email: "Email Address",
    password: "Password",
    forgot_password: "Forgot Password?",
    no_account: "Don't have an account?",
    full_name: "Full Name",
    verify_title: "Verify Your Email",
    verify_subtitle: "We've sent a 6-digit code to your email.",
    resend_code: "Resend Code",
    code_expired: "Code Expired",
    who_are_you: "Who are you?",
    patient: "Patient",
    doctor: "Doctor",
    continue: "Continue",
    tell_us_about_you: "Tell us about yourself",
    health_background: "Health background",
    complete_setup: "Complete Setup",
    next: "Next →",
    age: "Age",
    gender: "Gender",
    blood_group: "Blood Group",
    male: "Male",
    female: "Female",
    other: "Other",
    known_conditions: "Known Conditions",
    allergies: "Known Allergies",
    emergency_contact: "Emergency Contact",
    contact_name: "Name",
    contact_phone: "Phone Number",

    // Home
    good_morning: "Good morning",
    good_afternoon: "Good afternoon",
    good_evening: "Good evening",
    health_summary: "Health Summary",
    recent_sessions: "Recent Triages",
    no_sessions_yet: "No triage history yet",
    no_sessions_body: "Complete your first triage to see results here.",
    start_triage: "Start Triage",
    view_all: "See history →",
    ready_to_help: "Ready to help",
    last_session: "Last triage session",
    how_feeling: "How are you feeling today?",

    // Triage
    choose_method: "Choose an input method",
    voice_input: "Voice",
    text_input: "Text",
    image_input: "Image",
    video_input: "Video",
    voice_desc: "Speak your symptoms",
    text_desc: "Type about how you feel",
    image_desc: "Show visual symptoms",
    listening: "Listening...",
    release_to_send: "Release to send",
    type_reply: "Type a reply...",
    analyzing: "Analyzing your health...",
    session_title: "Triage Session",

    // Results
    your_result: "Your Result",
    seek_help_now: "Seek Help Now",
    moderate_risk: "Moderate Risk",
    low_risk: "Low Risk",
    what_this_means: "What this means",
    symptoms_detected: "Detected Symptoms",
    ai_assessment: "AI Assessment",
    recommended_steps: "Next Steps",
    emergency_resources: "Emergency Resources",
    call_ambulance: "Call Ambulance (102)",
    national_emergency: "National Emergency (112)",
    find_hospital: "Find Nearby Hospital",
    opens_maps: "Opens Google Maps",
    alert_contact: "Alert Emergency Contact",
    download_report: "Download Report",
    send_to_doctor: "Send to Doctor",
    select_doctor: "Select Doctor",
    delete_report: "Delete Report",
    delete_confirm: "Are you sure you want to delete this report?",
    report_deleted: "Report Deleted Successfully",
    find_emergency_help: "Emergency SOS",
    report_sent: "Report Sent Successfully",
    disclaimer: "AI-generated assessment. Not a clinical diagnosis. In case of emergency, call 102/911.",
    skip_sos: "Skip SOS",
    reports: "Your Reports",

    // SOS
    emergency: "Emergency",
    seek_immediate_help: "Seek immediate medical attention",
    im_safe: "I'm Safe Now",
    are_you_sure: "Are you sure you want to dismiss the SOS?",

    // Reports
    reports_title: "Your Reports",
    no_reports: "No Reports Yet",
    no_reports_body: "Your triage history and AI assessments will appear here.",
    doctor_reviewed: "Doctor reviewed ✓",
    pending_review: "Pending Review",
    filter_all: "All",
    filter_high: "High",
    filter_medium: "Med",
    filter_low: "Low",

    // Profile
    profile_title: "Profile",
    preferences: "Preferences",
    language: "Language",
    notifications: "Notifications",
    dark_mode: "Dark Mode",
    account: "Account",
    edit_profile: "Edit Profile",
    privacy: "Privacy Policy",
    about: "About Us",
    terms: "Terms of Service",
    rate_app: "Rate App",
    danger_zone: "Danger Zone",
    delete_account: "Delete Account",
    log_out: "Log Out",
    log_out_confirm: "Are you sure you want to log out?",
    cancel: "Cancel",

    // Errors
    error_generic: "Something went wrong. Please try again.",
    error_no_internet: "No internet connection.",
    error_image_upload: "Failed to upload image.",
    error_ai_connection: "Failed to connect to AI engine.",
    retry: "Retry",
    internet_required: "Internet required for triage.",

    // Misc
    notif_doctor_reviewed_title: "Report Reviewed",
    notif_doctor_reviewed_body: "A doctor has reviewed your triage report. Tap to view.",
    incomplete_triage: "Continue Triage?",
    incomplete_triage_body: "You were in the middle of a triage session.",
    continue_session: "Resume",
    start_fresh: "Discard",
    doctor_web_only: "Doctor accounts are managed via the MediTriage web portal. Please sign in at Website.",
    permission_required: "Permission required",
    camera_permission: "MediTriage needs camera access.",
    mic_permission: "MediTriage needs microphone access.",
    photo_permission: "Allow MediTriage to access your photos/videos.",
    coming_soon: "Coming Soon",
    log_out: "Log Out",
    log_out_confirm: "Are you sure you want to log out?",

    // Ambulance
    ambulance_operator: "Ambulance Operator",
    ambulance_subtitle: "Respond to emergency triage alerts",
    vehicle_details: "Vehicle Details",
    vehicle_number: "Vehicle Number",
    vehicle_type: "Vehicle Type",
    ready_to_save_lives: "Ready to save lives",
    online_status: "You are ONLINE — receiving alerts",
    offline_status: "You are OFFLINE — not receiving alerts",
    no_active_alerts: "No active alerts",
    notified_on_high_risk: "You will be notified when HIGH risk patients need help",
    accept: "Accept",
    dismiss: "Dismiss",
    arrived_at_patient: "I've Arrived at Patient",
    patient_on_board: "Patient On Board — Start Transport",
    complete_ride: "Complete Ride — Patient Delivered",
    cancel_ride: "Cancel Ride",
  },
  hi: {
    // Auth screens
    splash_title: "MediTriage AI",
    splash_tagline: "आपका निजी स्वास्थ्य सहायक",
    splash_card1_title: "AI विश्लेषण",
    splash_card1_body: "आधुनिक AI का उपयोग करके आपके लक्षणों का उन्नत मूल्यांकन।",
    splash_card2_title: "डॉक्टर द्वारा समीक्षा",
    splash_card2_body: "हर उच्च-जोखिम मामले की प्रमाणित डॉक्टरों द्वारा जांच की जाती है।",
    splash_card3_title: "सुरक्षित और निजी",
    splash_card3_body: "आपका स्वास्थ्य डेटा एन्क्रिप्टेड और पूरी तरह से गोपनीय है।",
    get_started: "शुरू करें",
    already_have_account: "क्या आपके पास पहले से खाता है?",
    welcome_back: "वापसी पर स्वागत है",
    sign_in: "साइन इन करें",
    sign_up: "साइन अप करें",
    email: "ईमेल पता",
    password: "पासवर्ड",
    forgot_password: "पासवर्ड भूल गए?",
    no_account: "खाता नहीं है?",
    full_name: "पूरा नाम",
    verify_title: "अपना ईमेल सत्यापित करें",
    verify_subtitle: "हमने आपके ईमेल पर 6 अंकों का कोड भेजा है।",
    resend_code: "कोड पुनः भेजें",
    code_expired: "कोड की अवधि समाप्त",
    who_are_you: "आप कौन हैं?",
    patient: "मरीज",
    doctor: "डॉक्टर",
    continue: "जारी रखें",
    tell_us_about_you: "अपने बारे में बताएं",
    health_background: "स्वास्थ्य पृष्ठभूमि",
    complete_setup: "सेटअप पूरा करें",
    next: "अगला →",
    age: "उम्र",
    gender: "लिंग",
    blood_group: "रक्त समूह",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    known_conditions: "ज्ञात बीमारियां",
    allergies: "ज्ञात एलर्जी",
    emergency_contact: "आपातकालीन संपर्क",
    contact_name: "नाम",
    contact_phone: "फोन नंबर",

    // Home
    good_morning: "सुप्रभात",
    good_afternoon: "शुभ दोपहर",
    good_evening: "शुभ संध्या",
    health_summary: "स्वास्थ्य सारांश",
    recent_sessions: "हाल की जांच",
    no_sessions_yet: "अभी तक कोई जांच इतिहास नहीं है",
    no_sessions_body: "परिणाम देखने के लिए अपनी पहली जांच पूरी करें।",
    start_triage: "जांच शुरू करें",
    view_all: "इतिहास देखें →",
    ready_to_help: "मदद के लिए तैयार",
    last_session: "पिछली जांच",
    how_feeling: "आज आप कैसा महसूस कर रहे हैं?",

    // Triage
    choose_method: "इनपुट तरीका चुनें",
    voice_input: "आवाज",
    text_input: "लेख",
    image_input: "फोटो",
    video_input: "वीडियो",
    voice_desc: "अपने लक्षण बोलें",
    text_desc: "अपनी स्थिति के बारे में लिखें",
    image_desc: "लक्षणों की फोटो दिखाएं",
    listening: "सुन रहे हैं...",
    release_to_send: "भेजने के लिए छोड़ें",
    type_reply: "जवाब लिखें...",
    analyzing: "आपके स्वास्थ्य का विश्लेषण हो रहा है...",
    session_title: "जांच सत्र",

    // Results
    your_result: "आपका परिणाम",
    seek_help_now: "तुरंत मदद लें",
    moderate_risk: "मध्यम जोखिम",
    low_risk: "कम जोखिम",
    what_this_means: "इसका क्या मतलब है",
    symptoms_detected: "पाए गए लक्षण",
    ai_assessment: "AI मूल्यांकन",
    recommended_steps: "अगले कदम",
    emergency_resources: "आपातकालीन संसाधन",
    call_ambulance: "एम्बुलेंस (102)",
    national_emergency: "राष्ट्रीय आपातकाल (112)",
    find_hospital: "नजदीकी अस्पताल खोजें",
    opens_maps: "गूगल मैप्स खुलेगा",
    alert_contact: "आपातकालीन संपर्क को सूचित करें",
    download_report: "रिपोर्ट डाउनलोड करें",
    send_to_doctor: "डॉक्टर को भेजें",
    select_doctor: "डॉक्टर चुनें",
    delete_report: "रिपोर्ट हटाएं",
    delete_confirm: "क्या आप वाकई इस रिपोर्ट को हटाना चाहते हैं?",
    report_deleted: "रिपोर्ट सफलतापूर्वक हटा दी गई",
    find_emergency_help: "आपातकालीन SOS",
    report_sent: "रिपोर्ट सफलतापूर्वक भेजी गई",
    disclaimer: "AI-जनित विश्लेषण। यह कोई नैदानिक ​​निदान नहीं है। आपात स्थिति में 102/911 पर कॉल करें।",
    skip_sos: "SOS छोड़ें",
    reports: "आपकी रिपोर्ट",

    // SOS
    emergency: "आपातकाल",
    seek_immediate_help: "तुरंत चिकित्सा सहायता लें",
    im_safe: "मैं अब सुरक्षित हूँ",
    are_you_sure: "क्या आप वाकई SOS को बंद करना चाहते हैं?",

    // Reports
    reports_title: "आपकी रिपोर्ट",
    no_reports: "अभी तक कोई रिपोर्ट नहीं",
    no_reports_body: "आपकी जांच का इतिहास और AI मूल्यांकन यहाँ दिखाई देगा।",
    doctor_reviewed: "डॉक्टर द्वारा जांचा गया ✓",
    pending_review: "समीक्षा लंबित",
    filter_all: "सब",
    filter_high: "उच्च",
    filter_medium: "मध्यम",
    filter_low: "कम",

    // Profile
    profile_title: "प्रोफ़ाइल",
    preferences: "प्राथमिकताएं",
    language: "भाषा",
    notifications: "सूचनाएं",
    dark_mode: "डार्क मोड",
    account: "खाता",
    edit_profile: "प्रोफ़ाइल बदलें",
    privacy: "गोपनीयता नीति",
    about: "हमारे बारे में",
    terms: "सेवा की शर्तें",
    rate_app: "ऐप को रेट करें",
    danger_zone: "खतरे का क्षेत्र",
    delete_account: "खाता हटाएं",
    log_out: "लॉग आउट",
    log_out_confirm: "क्या आप वाकई लॉग आउट करना चाहते हैं?",
    cancel: "रद्द करें",

    // Errors
    error_generic: "कुछ गलत हो गया। कृपया पुनः प्रयास करें।",
    error_no_internet: "इंटरनेट कनेक्शन नहीं है।",
    error_image_upload: "फोटो अपलोड करने में विफल।",
    error_ai_connection: "AI इंजन से जुड़ने में विफल।",
    retry: "पुनः प्रयास करें",
    internet_required: "जांच के लिए इंटरनेट आवश्यक है।",

    // Misc
    notif_doctor_reviewed_title: "रिपोर्ट जांची गई",
    notif_doctor_reviewed_body: "एक डॉक्टर ने आपकी रिपोर्ट जांची है। देखने के लिए टैप करें।",
    incomplete_triage: "जांच जारी रखें?",
    incomplete_triage_body: "आप एक जांच सत्र के बीच में थे।",
    continue_session: "जारी रखें",
    start_fresh: "हटाएं",
    doctor_web_only: "डॉक्टर खातों का प्रबंधन MediTriage वेब पोर्टल के माध्यम से किया जाता है। कृपया वेबसाइट पर साइन इन करें।",
    permission_required: "अनुमति की आवश्यकता",
    camera_permission: "MediTriage को कैमरे तक पहुंच की आवश्यकता है।",
    mic_permission: "MediTriage को माइक्रोफ़ोन तक पहुंच की आवश्यकता है।",
    photo_permission: "MediTriage को आपकी फ़ोटो/वीडियो तक पहुंचने दें।",
    coming_soon: "जल्द आ रहा है",
    log_out: "लॉगआउट",
    log_out_confirm: "क्या आप वाकई लॉग आउट करना चाहते हैं?",

    // Ambulance
    ambulance_operator: "एम्बुलेंस ऑपरेटर",
    ambulance_subtitle: "आपातकालीन ट्राइएज अलर्ट का उत्तर दें",
    vehicle_details: "वाहन विवरण",
    vehicle_number: "वाहन नंबर",
    vehicle_type: "वाहन का प्रकार",
    ready_to_save_lives: "जान बचाने के लिए तैयार",
    online_status: "आप ऑनलाइन हैं — अलर्ट प्राप्त कर रहे हैं",
    offline_status: "आप ऑफलाइन हैं — अलर्ट प्राप्त नहीं कर रहे हैं",
    no_active_alerts: "कोई सक्रिय अलर्ट नहीं",
    notified_on_high_risk: "जब उच्च जोखिम वाले मरीजों को मदद की आवश्यकता होगी तो आपको सूचित किया जाएगा",
    accept: "स्वीकार करें",
    dismiss: "खारिज करें",
    arrived_at_patient: "मैं मरीज के पास पहुँच गया हूँ",
    patient_on_board: "मरीज सवार है — परिवहन शुरू करें",
    complete_ride: "राइड पूरी करें — मरीज अस्पताल पहुँचा दिया गया",
    cancel_ride: "राइड रद्द करें",
  }
};
